// build-docs.mjs — 把 web/docs/usage/**/*.md 在构建期聚合成一个 TS 模块。
//
// 为什么需要它:new-api 用 Rsbuild/Rspack,没有 Vite 的 import.meta.glob,
// 也没有配 raw-.md 导入 loader。所以用这个 Node 脚本遍历 md 目录,
// 生成 web/src/features/docs/docs.generated.ts(类比已提交的 routeTree.gen.ts)。
// package.json 的 predev/prebuild 会自动跑它;改了 md 重跑 dev/build 即重生。
//
// 逻辑移植自 PAR 的 docsLoader.ts + plugins/llmsTxt.ts(walkMd / 分组 / 排序),
// 但输出 TS 而非 llms.txt。

import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DOCS_DIR = join(__dirname, '..', 'docs', 'usage')
const OUT_FILE = join(__dirname, '..', 'src', 'features', 'docs', 'docs.generated.ts')

/**
 * @typedef {{ slug: string, title: string, content: string, group: string, order: number }} DocEntry
 */

const GROUP_ORDER = {
  index: 0,
  overview: 1,
  cli: 2,
  api: 3,
  integrations: 4,
}

function walkMd(dir, base, out = []) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry)
    const st = statSync(p)
    if (st.isDirectory()) {
      walkMd(p, base, out)
    } else if (entry.endsWith('.md')) {
      const rel = relative(base, p).replaceAll('\\', '/')
      const content = readFileSync(p, 'utf8')
      const slugRaw = rel.replace(/\.md$/, '')
      const slug = slugRaw.toUpperCase() === 'README' ? '' : slugRaw
      out.push({
        slug,
        title: parseTitle(content, slug || 'docs'),
        content,
        group: classifyGroup(slug),
        order: orderOf(slug),
      })
    }
  }
  return out
}

function parseTitle(md, fallback) {
  const m = md.match(/^#\s+(.+?)\s*$/m)
  if (!m) return fallback
  // 去掉 "01 — " / "00 - " 这类序号前缀
  return m[1].replace(/^\d+\s*[—-]\s*/, '').trim()
}

function classifyGroup(slug) {
  if (slug === '') return 'index'
  if (slug === '00-quickstart') return 'overview'
  if (slug.startsWith('cli/')) return 'cli'
  if (slug.startsWith('integrations/')) return 'integrations'
  return 'api'
}

function orderOf(slug) {
  if (slug === '') return -1
  const m = slug.match(/(\d+)/)
  return m ? Number.parseInt(m[1], 10) : 999
}

function sortDocs(docs) {
  return [...docs].sort((a, b) => {
    if (a.group !== b.group) return GROUP_ORDER[a.group] - GROUP_ORDER[b.group]
    if (a.group === 'integrations') return a.slug.localeCompare(b.slug)
    return a.order - b.order
  })
}

function toJSON(value) {
  // JSON.stringify 已能安全转义 md 里的反引号/反斜杠/控制字符;再包成 TS 字面量。
  return JSON.stringify(value)
}

function main() {
  const docs = sortDocs(walkMd(DOCS_DIR, DOCS_DIR))
  const lines = []
  lines.push('// AUTO-GENERATED by scripts/build-docs.mjs — do not edit by hand.')
  lines.push('// Source: web/docs/usage/**/*.md. Re-run `bun run dev`/`bun run build` to regenerate.')
  lines.push('')
  lines.push('export type DocGroup = \'index\' | \'overview\' | \'cli\' | \'api\' | \'integrations\'')
  lines.push('')
  lines.push('export interface DocEntry {')
  lines.push('  slug: string')
  lines.push('  title: string')
  lines.push('  content: string')
  lines.push('  group: DocGroup')
  lines.push('  order: number')
  lines.push('}')
  lines.push('')
  lines.push('export const DOC_ENTRIES: DocEntry[] = [')
  for (const d of docs) {
    lines.push('  {')
    lines.push(`    slug: ${toJSON(d.slug)},`)
    lines.push(`    title: ${toJSON(d.title)},`)
    lines.push(`    group: ${toJSON(d.group)},`)
    lines.push(`    order: ${toJSON(d.order)},`)
    lines.push(`    content: ${toJSON(d.content)},`)
    lines.push('  },')
  }
  lines.push(']')
  lines.push('')

  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, lines.join('\n'))
  console.log(
    `[build-docs] wrote ${docs.length} doc entries → ${relative(join(__dirname, '..'), OUT_FILE)}`,
  )
}

main()
